
name: ph_coms_${ENV_NAME}

services:

  web-php-coms:
    image: nginx:latest
    restart: always
    container_name: ph_coms_web_${ENV_NAME}
    expose:
      - "80"
    volumes:
      - ./app/coms:/var/www/html
      - ./web-coms/default.conf:/etc/nginx/conf.d/default.conf
      - ./web-coms/.htpasswd-coms:/etc/nginx/.htpasswd-coms
    environment:
      VIRTUAL_HOST:
        ${COMS_DOMAIN_NAME},
    networks:
      - frontend
      - phpfpm-coms
    links:
      - php-fpm-coms

  php-fpm-coms:
    restart: always
    container_name: ph_coms_php_${ENV_NAME}
    build: 
      context: ./php-fpm-coms
      dockerfile: Dockerfile_PhpFpm
    expose:
      - "9000"
    volumes:
      - ./app/coms:/var/www/html
    user: "www-data:www-data"
    networks:
      - phpfpm-coms
      - pg
      - mail

  postgres:
    restart: always
    container_name: ph_coms_pg_${ENV_NAME}
    build: 
      context: ./pg
      dockerfile: Dockerfile_Pg
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    expose:
      - "5432"
    networks:
      - pg

  postfix:
    restart: always
    container_name: ph_coms_mail_${ENV_NAME}
    #image: catatnight/postfix:latest
    #image: my_postfix
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    expose:
      - "25"
    environment:
      maildomain: st.physcon.ru
      smtp_user: sender:love
    volumes:
      - ./data/domainkeys:/etc/opendkim/domainkeys
    networks:
      - mail

networks:
  frontend:
    external: true 
    name: frontend 
  phpfpm-coms:
  pg:
  mail:

 
