
name: ph_coms_${ENV_NAME}

services:

  nginx:
    # image: nginx:latest
    restart: always
    container_name: ph_coms_web_${ENV_NAME}
    build: 
      context: ./nginx
      dockerfile: Dockerfile_Nginx
    expose:
      - "80"
    volumes:
      - ./app/coms:/var/www/html
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/.htpasswd-coms:/etc/nginx/.htpasswd-coms
      - backup:/data/backup
    secrets:
      - htpasswd-coms
    environment:
      VIRTUAL_HOST:
        ${COMS_DOMAIN_NAME},
    networks:
      - frontend
      - php
    links:
      - php-fpm

  php-fpm:
    restart: always
    container_name: ph_coms_php_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpFpm
    expose:
      - "9000"
    volumes:
      - ./app/coms:/var/www/html
      # - ./data/papers:/data/papers
      - coms-papers:/data/papers
      - backup:/data/backup
    # user: "www-data:www-data"
    networks:
      - php
      - pg
      - smtp

  php-cron:
    restart: always
    container_name: ph_coms_cron_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpCron
    volumes:
      - ./app/coms:/var/www/html
      # - ./data/papers:/data/papers
      - coms-papers:/data/papers
      # - ./data/log/cron:/var/log/cron
    # user: "www-data:www-data"
    networks:
      - php
      - pg
      - smtp

  postgres:
    restart: always
    container_name: ph_coms_pg_${ENV_NAME}
    build: 
      context: ./pg
      dockerfile: Dockerfile_Pg
    volumes:
      - pg-data:/var/lib/postgresql/data
      - backup:/data/backup
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    expose:
      - "5432"
    networks:
      - pg

  postfix:
    restart: always
    container_name: ph_coms_mail_${ENV_NAME}
    #image: catatnight/postfix:latest
    #image: my_postfix
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    expose:
      - "25"
    environment:
      maildomain: ${IPACS_DOMAIN_NAME}
      smtp_user: sender:love
    # volumes:
      # - ./data/domainkeys:/etc/opendkim/domainkeys
      # - opendkim-domainkeys:/etc/opendkim/domainkeys
    secrets:
      - mail.private
    networks:
      - smtp

secrets:
  mail.private:
    file: .secrets/domainkeys/mail.private
  htpasswd-coms:
    file: .secrets/web/htpasswd-coms

volumes:
  pg-data:
  coms-papers:
  opendkim-domainkeys:
  backup:

networks:
  frontend:
    external: true 
    name: frontend 
  php:
  pg:
  smtp:


