
name: ph_coms_${ENV_NAME}

services:

  nginx:
    image: nginx:latest
    restart: always
    container_name: ph_coms_web_${ENV_NAME}
    expose:
      - "80"
    volumes:
      - ./app/coms:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd-coms:/etc/nginx/.htpasswd-coms
    environment:
      VIRTUAL_HOST:
        ${COMS_DOMAIN_NAME},
    networks:
      - frontend
      - php
    links:
      - php-fpm

  php-fpm:
    restart: always
    container_name: ph_coms_php_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpFpm
    expose:
      - "9000"
    volumes:
      - ./app/coms:/var/www/html
      - ./data/papers:/data/papers
    user: "www-data:www-data"
    networks:
      - php
      - pg
      - smtp

  php-cron:
    restart: always
    container_name: ph_cron_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpCron
    volumes:
      - ./app/coms:/var/www/html
      - ./data/papers:/data/papers
      - ./data/log/cron:/var/log/cron
    # user: "www-data:www-data"
    networks:
      - php
      - pg
      - smtp

  postgres:
    restart: always
    container_name: ph_coms_pg_${ENV_NAME}
    build: 
      context: ./pg
      dockerfile: Dockerfile_Pg
    volumes:
      # - ./data/pg:/var/lib/postgresql/data
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    expose:
      - "5432"
    networks:
      - pg

  postfix:
    restart: always
    container_name: ph_coms_mail_${ENV_NAME}
    #image: catatnight/postfix:latest
    #image: my_postfix
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    expose:
      - "25"
    environment:
      maildomain: st.physcon.ru
      smtp_user: sender:love
    volumes:
      - ./data/domainkeys:/etc/opendkim/domainkeys
    networks:
      - smtp


volumes:
  pg-data:

networks:
  frontend:
    external: true 
    name: frontend 
  php:
  pg:
  smtp:

 
