FROM php:7-fpm

RUN apt-get update

# Install PDO and PGSQL Drivers
RUN apt-get install -y libpq-dev \
  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
  && docker-php-ext-install pdo pdo_pgsql pgsql

RUN echo "security.limit_extensions = .html .php" >> /usr/local/etc/php-fpm.d/www.conf
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY ./php-overrides.ini $PHP_INI_DIR/conf.d/

# RUN chown www-data /var/www/html/coms/papers
# RUN chown www-data /var/www/html/coms/papers/*


